#!/usr/bin/env python3
"""Sound effects the DS English release added: SE04F and SE050, two sounds from
the GBA sequels (the DS banks are named BANK_AGB_SE04F / BANK_AGB_SE050). The
DS script plays them as songs 121 and 122; here they become songs 111 and 112,
appended to the GBA song table (port_script.py maps the ids).
Each is one 8-bit PCM sample, played once at its own rate, as on the DS.
usage: port_new_sounds.py DS_sound_data.sdat
writes sound/direct_sound_samples/en_se04f.bin, en_se050.bin and data/en_sound.s"""
import sys, os, struct
import ndspy.soundArchive as sa
ROOT = os.path.join(os.path.dirname(__file__), '..', '..')
SOUNDS = [  # DS song, GBA song, name; GBA SE03F is VOL 70 where the DS plays it at 90
    (121, 111, 'SE04F'),
    (122, 112, 'SE050'),
]
sdat = sa.SDAT.fromFile(sys.argv[1])
asm = ['@ generated by tools/en/port_new_sounds.py', '\t.include "asm/macros.inc"', '\t.section en_data, "a"', '']
for ds, gba, name in SOUNDS:
    sname, seq = sdat.sequences[ds]
    assert sname == name, sname
    seq.parse()
    notes = [e for e in seq.events if type(e).__name__ == 'NoteSequenceEvent']
    bname, bank = sdat.banks[seq.bankID]
    inst = bank.instruments[0].noteDefinition
    assert len(notes) == 1 and notes[0].pitch == inst.pitch == 60      # played at the sample's own rate
    wname, war = sdat.waveArchives[bank.waveArchiveIDs[0]]
    w = war.waves[inst.waveID]
    assert w.waveType == 0 and not w.isLooped, 'expected one-shot 8-bit PCM'
    pcm = bytes(w.data)
    fn = 'en_%s.bin' % name.lower()
    hdr = struct.pack('<HHIII', 0, 0, w.sampleRate * 1024, 0, len(pcm))
    open(os.path.join(ROOT, 'sound/direct_sound_samples', fn), 'wb').write(hdr + pcm + b'\0')
    vol = round(seq.volume * 70 / 90)
    sym = 'gEnSong%s' % name
    asm += ['\t.align 2', '%s_voice:' % sym,
            '\tvoice_directsound 60, 0, %s_sample, 255, 0, 255, 0' % sym, '',
            '%s_track:' % sym,
            '\t.byte 0xBC, 0x00, 0xBB, 0x3C, 0xBD, 0x00, 0xBE, %d, 0xBF, 0x40' % vol,
            '\t.byte 0xFF, 0x3C, 0x7F, 0xB0, 0xB1', '',
            '\t.align 2', '\t.global %s' % sym, '%s:' % sym,
            '\t.byte 1, 0, 127, 128', '\t.word %s_voice' % sym, '\t.word %s_track' % sym, '',
            '\t.align 2', '%s_sample:' % sym, '\t.incbin "sound/direct_sound_samples/%s"' % fn, '']
    print('%s (DS song %d -> GBA song %d): %d Hz, %.2fs, volume %d' % (name, ds, gba, w.sampleRate, len(pcm) / w.sampleRate, vol))
open(os.path.join(ROOT, 'data/en_sound.s'), 'w').write('\n'.join(asm))
