#!/usr/bin/env python3
"""Keep the original graphics layout intact.

The game code reaches most graphics through hard-coded ROM addresses
(include/graphics.h), so an asset whose size changes would shift everything
after it. Instead, every asset we replace keeps its original bytes at the
original address (graphics_orig/) and the English version is linked into the
expanded ROM area under <label>_en; the address macro is pointed there.

usage: relocate_assets.py PRISTINE_DECOMP_DIR   (a built, unmodified pwaa1 checkout)
Run after changing any graphics; it is idempotent."""
import os, re, sys, shutil
ROOT = os.path.join(os.path.dirname(__file__), '..', '..')
PRISTINE = sys.argv[1]
gs_path = os.path.join(ROOT, 'data/graphics.s')
gs = open(gs_path).read()
items = re.findall(r'\.global (\w+)\n\1:[^\n]*\n\s*\.incbin "([^"]+)"(?!\n\s*\.incbin)', gs)
# Labels that cover several files (talk/location menu plates) are edited in
# place; their files must keep their size.
for block in re.findall(r'\.global \w+\n\w+:[^\n]*\n((?:\s*\.incbin "[^"]+"\n){2,})', gs):
    for f in re.findall(r'"([^"]+)"', block):
        new_f = os.path.join(ROOT, f); old_f = os.path.join(PRISTINE, f)
        if os.path.exists(new_f) and os.path.exists(old_f):
            assert os.path.getsize(new_f) == os.path.getsize(old_f), 'size changed: ' + f
changed = []
for label, f in items:
    real = f.replace('graphics_orig/', 'graphics/', 1)
    new = os.path.join(ROOT, real); old = os.path.join(PRISTINE, real)
    if os.path.exists(new) and os.path.exists(old) and open(new, 'rb').read() != open(old, 'rb').read():
        changed.append((label, real))
# 1. original bytes stay at the original address
for label, real in changed:
    dst = os.path.join(ROOT, real.replace('graphics/', 'graphics_orig/', 1))
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copy(os.path.join(PRISTINE, real), dst)
    gs = re.sub(r'(\.global %s\n%s:[^\n]*\n\s*\.incbin ")[^"]+(")' % (label, label),
                r'\g<1>%s\g<2>' % real.replace('graphics/', 'graphics_orig/', 1), gs)
open(gs_path, 'w').write(gs)
# 2. English versions in the expanded area
with open(os.path.join(ROOT, 'data/en_graphics.s'), 'w') as o:
    o.write('@ generated by tools/en/relocate_assets.py\n\t.section en_data, "a"\n')
    for label, real in changed:
        o.write('\n\t.align 2\n\t.global %s_en\n%s_en:\n\t.incbin "%s"\n' % (label, label, real))
# 3. point the address macros at the English versions
h_path = os.path.join(ROOT, 'include/graphics.h')
h = open(h_path).read()
h = re.sub(r'\n*// English patch relocations.*?// end English patch relocations\n+', '\n\n', h, flags=re.S)
# assets that are back to their original bytes: their macros go back to the
# original address (graphics_orig/ keeps the original bytes there anyway)
ph = open(os.path.join(PRISTINE, 'include/graphics.h')).read()
names = set(l for l, r in changed)
for label in re.findall(r'#define (\w+) \(\(\w+\s*\*\)\1_en\)', h):
    if label not in names:
        m = re.search(r'#define %s \([^\n]*' % label, ph)
        h = re.sub(r'#define %s \(\(\w+\s*\*\)%s_en\)' % (label, label), lambda _: m.group(0), h)
        print('back to the original:', label)
block = ['// English patch relocations (tools/en/relocate_assets.py)']
for label, real in changed:
    m = re.search(r'#define %s \(\((\w+)\s*\*\)' % label, h)
    if not m:
        print('warning: no address macro for %s; the code would still see the original' % label)
        continue
    t = m.group(1)
    h = re.sub(r'#define %s \(\(%s\s*\*\)\([^)]*\)\)' % (label, t), '#define %s ((%s*)%s_en)' % (label, t, label), h)
    block.append('extern u8 %s_en[];' % label)
block.append('// end English patch relocations')
h = h.replace('#define GFX_BASE_ADDR', '\n'.join(block) + '\n\n#define GFX_BASE_ADDR', 1)
open(h_path, 'w').write(h)
print('relocated', len(changed), 'assets')
