@ generated by tools/en/port_gs3_court.py: the courtroom of Gyakuten Saiban 3
	.section en_data, "a"

	.align 2
	.global gEnCourtDefenseBench
gEnCourtDefenseBench:
	.incbin "graphics/en/court/defense_bench.8bpp.striped"

	.align 2
	.global gEnCourtProsecutionBench
gEnCourtProsecutionBench:
	.incbin "graphics/en/court/prosecution_bench.8bpp.striped"

	.align 2
	.global gEnCourtWitnessStand
gEnCourtWitnessStand:
	.incbin "graphics/en/court/witness_stand.8bpp.striped"

	.align 2
	.global gEnCourtJudgeSeat
gEnCourtJudgeSeat:
	.incbin "graphics/en/court/judge_seat.8bpp.striped"

	.align 2
	.global gEnCourtCoCounsel
gEnCourtCoCounsel:
	.incbin "graphics/en/court/co_counsel.8bpp.striped"

	.align 2
	.global gEnCourtCourtRoom
gEnCourtCourtRoom:
	.incbin "graphics/en/court/court_room.8bpp.striped"

	.align 2
	.global gEnCourtPan
gEnCourtPan:
	.incbin "graphics/en/court/court_pan.bin"
