@ generated by tools/en/make_effects.py
	.section en_data, "a"

	.align 2
	.global gEnBannerGfx
gEnBannerGfx:
	.incbin "graphics/en/effects/banner.gfx"

	.align 2
	.global gEnBannerSeq_testimony
gEnBannerSeq_testimony:
	.incbin "graphics/en/effects/banner_testimony.seq"

	.align 2
	.global gEnBannerSeq_cross
gEnBannerSeq_cross:
	.incbin "graphics/en/effects/banner_cross.seq"

	.align 2
	.global gEnBannerSeq_testimony_left
gEnBannerSeq_testimony_left:
	.incbin "graphics/en/effects/banner_testimony_left.seq"

	.align 2
	.global gEnBannerSeq_testimony_right
gEnBannerSeq_testimony_right:
	.incbin "graphics/en/effects/banner_testimony_right.seq"

	.align 2
	.global gEnBannerSeq_cross_left
gEnBannerSeq_cross_left:
	.incbin "graphics/en/effects/banner_cross_left.seq"

	.align 2
	.global gEnBannerSeq_cross_right
gEnBannerSeq_cross_right:
	.incbin "graphics/en/effects/banner_cross_right.seq"

	.align 2
	.global gEnBubbleGfx_objection
gEnBubbleGfx_objection:
	.incbin "graphics/en/effects/bubble_objection.gfx"

	.align 2
	.global gEnBubbleSeq_objection
gEnBubbleSeq_objection:
	.incbin "graphics/en/effects/bubble_objection.seq"

	.align 2
	.global gEnBubbleGfx_holdit
gEnBubbleGfx_holdit:
	.incbin "graphics/en/effects/bubble_holdit.gfx"

	.align 2
	.global gEnBubbleSeq_holdit
gEnBubbleSeq_holdit:
	.incbin "graphics/en/effects/bubble_holdit.seq"

	.align 2
	.global gEnBubbleGfx_takethat
gEnBubbleGfx_takethat:
	.incbin "graphics/en/effects/bubble_takethat.gfx"

	.align 2
	.global gEnBubbleSeq_takethat
gEnBubbleSeq_takethat:
	.incbin "graphics/en/effects/bubble_takethat.seq"

	.align 2
	.global gEnVerdictLetterTiles
gEnVerdictLetterTiles:
	.incbin "graphics/en/effects/verdict_letters.4bpp"

	.align 2
	.global gEnVerdictPalGuilty
gEnVerdictPalGuilty:
	.incbin "graphics/en/effects/verdict_guilty.gbapal"

	.align 2
	.global gEnVerdictPalNotGuilty
gEnVerdictPalNotGuilty:
	.incbin "graphics/en/effects/verdict_not_guilty.gbapal"
