@ generated by tools/en/relocate_assets.py
	.section en_data, "a"

	.align 2
	.global gPalTitleScreen_en
gPalTitleScreen_en:
	.incbin "graphics/title_screen.gbapal"

	.align 2
	.global gGfx8lzTitleScreen_en
gGfx8lzTitleScreen_en:
	.incbin "graphics/title_screen.8bpp.lz"

	.align 2
	.global gGfxSaveGameTiles_en
gGfxSaveGameTiles_en:
	.incbin "graphics/ui/message_box/save_game_tiles.4bpp"

	.align 2
	.global gGfx4bppNametags_en
gGfx4bppNametags_en:
	.incbin "graphics/ui/message_box/nametags.4bpp"

	.align 2
	.global gGfx4bppInvestigationActions_en
gGfx4bppInvestigationActions_en:
	.incbin "graphics/ui/investigation/action_buttons.4bpp"

	.align 2
	.global gGfx4bppTestimonyTextTiles_en
gGfx4bppTestimonyTextTiles_en:
	.incbin "graphics/ui/trial/testimony_text_tiles.4bpp"

	.align 2
	.global gGfxTrialPressPresentButtons_en
gGfxTrialPressPresentButtons_en:
	.incbin "graphics/ui/trial/press_present_buttons.4bpp"

	.align 2
	.global gGfxCourtRecordPresentBackText_en
gGfxCourtRecordPresentBackText_en:
	.incbin "graphics/ui/court_record/present_back_text.4bpp"

	.align 2
	.global gGfxCourtRecordProfilesText_en
gGfxCourtRecordProfilesText_en:
	.incbin "graphics/ui/court_record/profiles_text.4bpp"

	.align 2
	.global gGfxCourtRecordEvidenceText_en
gGfxCourtRecordEvidenceText_en:
	.incbin "graphics/ui/court_record/evidence_text.4bpp"

	.align 2
	.global gGfxNewGameContinue_en
gGfxNewGameContinue_en:
	.incbin "graphics/ui/new_game_continue.4bpp"

	.align 2
	.global gGfx4lzEpisodeSelectOptions_en
gGfx4lzEpisodeSelectOptions_en:
	.incbin "graphics/episode_select_options.4bpp.lz"

	.align 2
	.global gGfxFromSaveOrBeginning_en
gGfxFromSaveOrBeginning_en:
	.incbin "graphics/from_save_or_beginning_options.4bpp"

	.align 2
	.global gGfxSaveYesOrNo_en
gGfxSaveYesOrNo_en:
	.incbin "graphics/save_yes_no.4bpp"

	.align 2
	.global gGfxProfilesMiaFey0_description_en
gGfxProfilesMiaFey0_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/mia_fey_0.4bpp.lz"

	.align 2
	.global gGfxProfilesMayaFey0_description_en
gGfxProfilesMayaFey0_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/maya_fey_0.4bpp.lz"

	.align 2
	.global gGfxProfilesLarryButz0_description_en
gGfxProfilesLarryButz0_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/larry_butz_0.4bpp.lz"

	.align 2
	.global gGfxProfilesCindyStone_description_en
gGfxProfilesCindyStone_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/cindy_stone.4bpp.lz"

	.align 2
	.global gGfxProfilesFrankSahwit_description_en
gGfxProfilesFrankSahwit_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/frank_sahwit.4bpp.lz"

	.align 2
	.global gGfxProfilesWinstonPayne_description_en
gGfxProfilesWinstonPayne_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/winston_payne.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericAutopsyReport0_description_en
gGfxEvidenceGenericAutopsyReport0_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_autopsy_report_0.4bpp.lz"

	.align 2
	.global gGfxEvidenceTheThinker0_description_en
gGfxEvidenceTheThinker0_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/the_thinker_0.4bpp.lz"

	.align 2
	.global gGfxEvidenceCindyStonesPassport_description_en
gGfxEvidenceCindyStonesPassport_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/cindy_stones_passport.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericAffidavit0_description_en
gGfxEvidenceGenericAffidavit0_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_affidavit_0.4bpp.lz"

	.align 2
	.global gGfxProfilesMiaFey1_description_en
gGfxProfilesMiaFey1_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/mia_fey_1.4bpp.lz"

	.align 2
	.global gGfxProfilesMayaFey1_description_en
gGfxProfilesMayaFey1_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/maya_fey_1.4bpp.lz"

	.align 2
	.global gGfxProfilesMayaFey2_description_en
gGfxProfilesMayaFey2_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/maya_fey_2.4bpp.lz"

	.align 2
	.global gGfxProfilesMayaFey3_description_en
gGfxProfilesMayaFey3_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/maya_fey_3.4bpp.lz"

	.align 2
	.global gGfxProfilesMilesEdgeworth0_description_en
gGfxProfilesMilesEdgeworth0_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/miles_edgeworth_0.4bpp.lz"

	.align 2
	.global gGfxProfilesDickGumshoe_description_en
gGfxProfilesDickGumshoe_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/dick_gumshoe.4bpp.lz"

	.align 2
	.global gGfxProfilesAprilMay0_description_en
gGfxProfilesAprilMay0_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/april_may_0.4bpp.lz"

	.align 2
	.global gGfxProfilesAprilMay1_description_en
gGfxProfilesAprilMay1_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/april_may_1.4bpp.lz"

	.align 2
	.global gGfxProfilesAprilMay2_description_en
gGfxProfilesAprilMay2_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/april_may_2.4bpp.lz"

	.align 2
	.global gGfxProfilesReddWhite0_description_en
gGfxProfilesReddWhite0_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/redd_white_0.4bpp.lz"

	.align 2
	.global gGfxProfilesBellboy0_description_en
gGfxProfilesBellboy0_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/bellboy_0.4bpp.lz"

	.align 2
	.global gGfxProfilesBellboy1_description_en
gGfxProfilesBellboy1_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/bellboy_1.4bpp.lz"

	.align 2
	.global gGfxProfilesMarvinGrossberg_description_en
gGfxProfilesMarvinGrossberg_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/marvin_grossberg.4bpp.lz"

	.align 2
	.global gGfxEvidencePhoenixBadge_description_en
gGfxEvidencePhoenixBadge_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/phoenix_badge.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericAutopsyReport1_description_en
gGfxEvidenceGenericAutopsyReport1_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_autopsy_report_1.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericLetter0_description_en
gGfxEvidenceGenericLetter0_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_letter_0.4bpp.lz"

	.align 2
	.global gGfxEvidenceMayasCellphone_description_en
gGfxEvidenceMayasCellphone_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/mayas_cellphone.4bpp.lz"

	.align 2
	.global gGfxEvidenceGlassShards_description_en
gGfxEvidenceGlassShards_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/glass_shards.4bpp.lz"

	.align 2
	.global gGfxEvidenceTheThinker1_description_en
gGfxEvidenceTheThinker1_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/the_thinker_1.4bpp.lz"

	.align 2
	.global gGfxEvidenceTheThinker2_description_en
gGfxEvidenceTheThinker2_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/the_thinker_2.4bpp.lz"

	.align 2
	.global gGfxEvidenceMayaMemo_description_en
gGfxEvidenceMayaMemo_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/maya_memo.4bpp.lz"

	.align 2
	.global gGfxEvidenceNoteFromTheSafe_description_en
gGfxEvidenceNoteFromTheSafe_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/note_from_the_safe.4bpp.lz"

	.align 2
	.global gGfxEvidenceWiretap_description_en
gGfxEvidenceWiretap_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/wiretap.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericAffidavit1_description_en
gGfxEvidenceGenericAffidavit1_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_affidavit_1.4bpp.lz"

	.align 2
	.global gGfxProfilesMistyFey0_description_en
gGfxProfilesMistyFey0_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/misty_fey_0.4bpp.lz"

	.align 2
	.global gGfxProfilesReddWhite1_description_en
gGfxProfilesReddWhite1_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/redd_white_1.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericNewspaperClipping_description_en
gGfxEvidenceGenericNewspaperClipping_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_newspaper_clipping.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericPhoto0_description_en
gGfxEvidenceGenericPhoto0_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_photo_0.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericAffidavit2_description_en
gGfxEvidenceGenericAffidavit2_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_affidavit_2.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericAutopsyReport2_description_en
gGfxEvidenceGenericAutopsyReport2_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_autopsy_report_2.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericLetter1_description_en
gGfxEvidenceGenericLetter1_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_letter_1.4bpp.lz"

	.align 2
	.global gGfxEvidenceLottasCamera0_description_en
gGfxEvidenceLottasCamera0_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/lottas_camera_0.4bpp.lz"

	.align 2
	.global gGfxProfilesWillPowers_description_en
gGfxProfilesWillPowers_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/will_powers.4bpp.lz"

	.align 2
	.global gGfxProfilesWendyOldbag_description_en
gGfxProfilesWendyOldbag_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/wendy_oldbag.4bpp.lz"

	.align 2
	.global gGfxProfilesJackHammer_description_en
gGfxProfilesJackHammer_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/jack_hammer.4bpp.lz"

	.align 2
	.global gGfxProfilesPennyNichols_description_en
gGfxProfilesPennyNichols_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/penny_nichols.4bpp.lz"

	.align 2
	.global gGfxProfilesSalManella_description_en
gGfxProfilesSalManella_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/sal_manella.4bpp.lz"

	.align 2
	.global gGfxProfilesDeeVasquez_description_en
gGfxProfilesDeeVasquez_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/dee_vasquez.4bpp.lz"

	.align 2
	.global gGfxProfilesCodyHackins_description_en
gGfxProfilesCodyHackins_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/cody_hackins.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericAffidavit3_description_en
gGfxEvidenceGenericAffidavit3_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_affidavit_3.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericAutopsyReport3_description_en
gGfxEvidenceGenericAutopsyReport3_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_autopsy_report_3.4bpp.lz"

	.align 2
	.global gGfxEvidenceGlobalStudiosCardKey_description_en
gGfxEvidenceGlobalStudiosCardKey_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/global_studios_card_key.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericPhoto1_description_en
gGfxEvidenceGenericPhoto1_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_photo_1.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericPhoto2_description_en
gGfxEvidenceGenericPhoto2_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_photo_2.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericPhoto3_description_en
gGfxEvidenceGenericPhoto3_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_photo_3.4bpp.lz"

	.align 2
	.global gGfxEvidenceSteelSamuraiSpear0_description_en
gGfxEvidenceSteelSamuraiSpear0_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/steel_samurai_spear_0.4bpp.lz"

	.align 2
	.global gGfxEvidenceSteelSamuraiSpear1_description_en
gGfxEvidenceSteelSamuraiSpear1_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/steel_samurai_spear_1.4bpp.lz"

	.align 2
	.global gGfxEvidenceEmptyBottle0_description_en
gGfxEvidenceEmptyBottle0_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/empty_bottle_0.4bpp.lz"

	.align 2
	.global gGfxEvidenceKeyToCottage_description_en
gGfxEvidenceKeyToCottage_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/key_to_cottage.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericLetter2_description_en
gGfxEvidenceGenericLetter2_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_letter_2.4bpp.lz"

	.align 2
	.global gGfxEvidenceSteelSamuraiScript_description_en
gGfxEvidenceSteelSamuraiScript_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/steel_samurai_script.4bpp.lz"

	.align 2
	.global gGfxEvidenceMrMonkey_description_en
gGfxEvidenceMrMonkey_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/mr_monkey.4bpp.lz"

	.align 2
	.global gGfxEvidenceSteelSamuraiCards_description_en
gGfxEvidenceSteelSamuraiCards_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/steel_samurai_cards.4bpp.lz"

	.align 2
	.global gGfxEvidenceSteelSamuraiUltraRareCard_description_en
gGfxEvidenceSteelSamuraiUltraRareCard_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/steel_samurai_ultra_rare_card.4bpp.lz"

	.align 2
	.global gGfxEvidenceCodysSteelSamuraiScrapbook_description_en
gGfxEvidenceCodysSteelSamuraiScrapbook_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/codys_steel_samurai_scrapbook.4bpp.lz"

	.align 2
	.global gGfxEvidenceCodysDigitalCamera_description_en
gGfxEvidenceCodysDigitalCamera_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/codys_digital_camera.4bpp.lz"

	.align 2
	.global gGfxEvidencePlateWithSteakBones_description_en
gGfxEvidencePlateWithSteakBones_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/plate_with_steak_bones.4bpp.lz"

	.align 2
	.global gGfxEvidenceEmptyBottle1_description_en
gGfxEvidenceEmptyBottle1_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/empty_bottle_1.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericPhoto4_description_en
gGfxEvidenceGenericPhoto4_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_photo_4.4bpp.lz"

	.align 2
	.global gGfxEvidenceGlobalStudiosVan_description_en
gGfxEvidenceGlobalStudiosVan_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/global_studios_van.4bpp.lz"

	.align 2
	.global gGfxEvidenceEmptyPlate_description_en
gGfxEvidenceEmptyPlate_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/empty_plate.4bpp.lz"

	.align 2
	.global gGfxProfilesMilesEdgeworth1_description_en
gGfxProfilesMilesEdgeworth1_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/miles_edgeworth_1.4bpp.lz"

	.align 2
	.global gGfxProfilesLottaHart0_description_en
gGfxProfilesLottaHart0_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/lotta_hart_0.4bpp.lz"

	.align 2
	.global gGfxProfilesLottaHart1_description_en
gGfxProfilesLottaHart1_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/lotta_hart_1.4bpp.lz"

	.align 2
	.global gGfxProfilesLarryButz1_description_en
gGfxProfilesLarryButz1_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/larry_butz_1.4bpp.lz"

	.align 2
	.global gGfxProfilesRobertHammond_description_en
gGfxProfilesRobertHammond_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/robert_hammond.4bpp.lz"

	.align 2
	.global gGfxProfilesMistyFey1_description_en
gGfxProfilesMistyFey1_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/misty_fey_1.4bpp.lz"

	.align 2
	.global gGfxProfilesManfredVonKarma_description_en
gGfxProfilesManfredVonKarma_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/manfred_von_karma.4bpp.lz"

	.align 2
	.global gGfxProfilesGregoryEdgeworth_description_en
gGfxProfilesGregoryEdgeworth_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/gregory_edgeworth.4bpp.lz"

	.align 2
	.global gGfxProfilesOldMan0_description_en
gGfxProfilesOldMan0_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/old_man_0.4bpp.lz"

	.align 2
	.global gGfxProfilesOldMan1_description_en
gGfxProfilesOldMan1_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/old_man_1.4bpp.lz"

	.align 2
	.global gGfxEvidenceFirecrackers_description_en
gGfxEvidenceFirecrackers_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/firecrackers.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericAutopsyReport4_description_en
gGfxEvidenceGenericAutopsyReport4_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_autopsy_report_4.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericAutopsyReport5_description_en
gGfxEvidenceGenericAutopsyReport5_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_autopsy_report_5.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericAutopsyReport6_description_en
gGfxEvidenceGenericAutopsyReport6_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_autopsy_report_6.4bpp.lz"

	.align 2
	.global gGfxEvidenceLottasCamera1_description_en
gGfxEvidenceLottasCamera1_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/lottas_camera_1.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericPhoto5_description_en
gGfxEvidenceGenericPhoto5_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_photo_5.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericPhoto6_description_en
gGfxEvidenceGenericPhoto6_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_photo_6.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericPhoto7_description_en
gGfxEvidenceGenericPhoto7_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_photo_7.4bpp.lz"

	.align 2
	.global gGfxProfilesMistyFey2_description_en
gGfxProfilesMistyFey2_description_en:
	.incbin "graphics/evidence_profile_descriptions/profiles/misty_fey_2.4bpp.lz"

	.align 2
	.global gGfxEvidenceArticleGourdy_description_en
gGfxEvidenceArticleGourdy_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/article_gourdy.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericAffidavit4_description_en
gGfxEvidenceGenericAffidavit4_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_affidavit_4.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericPhoto8_description_en
gGfxEvidenceGenericPhoto8_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_photo_8.4bpp.lz"

	.align 2
	.global gGfxEvidenceBullet0_description_en
gGfxEvidenceBullet0_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/bullet_0.4bpp.lz"

	.align 2
	.global gGfxEvidenceBullet1_description_en
gGfxEvidenceBullet1_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/bullet_1.4bpp.lz"

	.align 2
	.global gGfxEvidencePistol_description_en
gGfxEvidencePistol_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/pistol.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericAffidavit5_description_en
gGfxEvidenceGenericAffidavit5_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_affidavit_5.4bpp.lz"

	.align 2
	.global gGfxEvidenceAirTube_description_en
gGfxEvidenceAirTube_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/air_tube.4bpp.lz"

	.align 2
	.global gGfxEvidenceMissile_description_en
gGfxEvidenceMissile_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/missile.4bpp.lz"

	.align 2
	.global gGfxEvidenceFishingPole_description_en
gGfxEvidenceFishingPole_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/fishing_pole.4bpp.lz"

	.align 2
	.global gGfxEvidenceMetalDetector_description_en
gGfxEvidenceMetalDetector_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/metal_detector.4bpp.lz"

	.align 2
	.global gGfxEvidencePolly_description_en
gGfxEvidencePolly_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/polly.4bpp.lz"

	.align 2
	.global gGfxEvidenceYannisSafe_description_en
gGfxEvidenceYannisSafe_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/yannis_safe.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericAutopsyReport7_description_en
gGfxEvidenceGenericAutopsyReport7_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_autopsy_report_7.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericPhoto9_description_en
gGfxEvidenceGenericPhoto9_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_photo_9.4bpp.lz"

	.align 2
	.global gGfxEvidenceGenericLetter3_description_en
gGfxEvidenceGenericLetter3_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/generic_letter_3.4bpp.lz"

	.align 2
	.global gGfxEvidenceDl6Bullet_description_en
gGfxEvidenceDl6Bullet_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/dl-6_bullet.4bpp.lz"

	.align 2
	.global gGfxEvidenceMissileAngry_description_en
gGfxEvidenceMissileAngry_description_en:
	.incbin "graphics/evidence_profile_descriptions/evidence/missile_angry.4bpp.lz"

	.align 2
	.global gGfx_BG011_GlobalStudiosStudioPath_en
gGfx_BG011_GlobalStudiosStudioPath_en:
	.incbin "graphics/striped_images/backgrounds/global_studios/studio_path.8bpp.striped"

	.align 2
	.global gGfx_BG012_GlobalStudiosStaffArea_en
gGfx_BG012_GlobalStudiosStaffArea_en:
	.incbin "graphics/striped_images/backgrounds/global_studios/staff_area.8bpp.striped"

	.align 2
	.global gGfx_BG031_BlueCorpCeoOffice_en
gGfx_BG031_BlueCorpCeoOffice_en:
	.incbin "graphics/striped_images/backgrounds/bluecorp_ceo_office.8bpp.striped"

	.align 2
	.global gGfx_BG045_EvidenceMayaPhoneCall1_en
gGfx_BG045_EvidenceMayaPhoneCall1_en:
	.incbin "graphics/striped_images/backgrounds/evidence/maya_phone_call_page_1.4bpp.striped"

	.align 2
	.global gGfx_BG046_EvidenceMayaPhoneCall2_en
gGfx_BG046_EvidenceMayaPhoneCall2_en:
	.incbin "graphics/striped_images/backgrounds/evidence/maya_phone_call_page_2.4bpp.striped"

	.align 2
	.global gGfx_BG048_EvidenceMayaPhoneCall3_en
gGfx_BG048_EvidenceMayaPhoneCall3_en:
	.incbin "graphics/striped_images/backgrounds/evidence/maya_phone_call_page_3.4bpp.striped"

	.align 2
	.global gGfx_BG059_Case3PinkPrincess_en
gGfx_BG059_Case3PinkPrincess_en:
	.incbin "graphics/striped_images/backgrounds/cutscenes/case3/pink_princess.8bpp.striped"

	.align 2
	.global gGfx_BG061_EvidenceGlobalStudiosDiagram_en
gGfx_BG061_EvidenceGlobalStudiosDiagram_en:
	.incbin "graphics/striped_images/backgrounds/evidence/global_studio_diagram.4bpp.striped"

	.align 2
	.global gGfx_BG063_Case3SteelSamurai_en
gGfx_BG063_Case3SteelSamurai_en:
	.incbin "graphics/striped_images/backgrounds/cutscenes/case3/steel_samurai.8bpp.striped"

	.align 2
	.global gGfx_BG067_CourtroomBackground_en
gGfx_BG067_CourtroomBackground_en:
	.incbin "graphics/striped_images/courtroom_background.4bpp.striped"

	.align 2
	.global gGfx_BG070_GourdLakeEntrance_en
gGfx_BG070_GourdLakeEntrance_en:
	.incbin "graphics/striped_images/gourd_lake_entrance.8bpp.striped"

	.align 2
	.global gGfx_BG071_GourdLakePark_en
gGfx_BG071_GourdLakePark_en:
	.incbin "graphics/striped_images/gourd_lake_park.8bpp.striped"

	.align 2
	.global gGfx_BG072_GourdLakeParkNoBalloon_en
gGfx_BG072_GourdLakeParkNoBalloon_en:
	.incbin "graphics/striped_images/gourd_lake_park_no_balloon.8bpp.striped"

	.align 2
	.global gGfx_BG077_GourdLakeBoatRental_en
gGfx_BG077_GourdLakeBoatRental_en:
	.incbin "graphics/striped_images/gourd_lake_boat_rental.8bpp.striped"

	.align 2
	.global gGfx_BG082_EvidenceDL6CaseFile1_en
gGfx_BG082_EvidenceDL6CaseFile1_en:
	.incbin "graphics/striped_images/backgrounds/evidence/dl6_case_file_page_1.4bpp.striped"

	.align 2
	.global gGfx_BG083_EvidenceDL6CaseFile2_en
gGfx_BG083_EvidenceDL6CaseFile2_en:
	.incbin "graphics/striped_images/backgrounds/evidence/dl6_case_file_page_2.4bpp.striped"

	.align 2
	.global gGfx_BG084_EvidenceDL6CaseFile3_en
gGfx_BG084_EvidenceDL6CaseFile3_en:
	.incbin "graphics/striped_images/backgrounds/evidence/dl6_case_file_page_3.4bpp.striped"

	.align 2
	.global gGfx_BG089_Case4Newspaper_en
gGfx_BG089_Case4Newspaper_en:
	.incbin "graphics/striped_images/case4_newspaper.8bpp.striped"

	.align 2
	.global gGfx_BG105_TrialWon_en
gGfx_BG105_TrialWon_en:
	.incbin "graphics/striped_images/trial_won.8bpp.striped"
