@ generated by tools/en/make_menus.py
	.section en_data, "a"

	.align 2
	.global gEnMenuBgTiles
gEnMenuBgTiles:
	.incbin "graphics/en/menu/menu_bg.4bpp"

	.align 2
	.global gEnMenuBgPal
gEnMenuBgPal:
	.incbin "graphics/en/menu/menu_bg.gbapal"

	.align 2
	.global gEnMenuMapSave
gEnMenuMapSave:
	.incbin "graphics/en/menu/map_save.bin"

	.align 2
	.global gEnMenuMapLoad
gEnMenuMapLoad:
	.incbin "graphics/en/menu/map_load.bin"

	.align 2
	.global gEnMenuMapClear
gEnMenuMapClear:
	.incbin "graphics/en/menu/map_clear.bin"

	.align 2
	.global gEnMenuButtonsShort
gEnMenuButtonsShort:
	.incbin "graphics/en/menu/buttons_short.4bpp"

	.align 2
	.global gEnMenuButtonsLong
gEnMenuButtonsLong:
	.incbin "graphics/en/menu/buttons_long.4bpp"

	.align 2
	.global gEnMenuBracket
gEnMenuBracket:
	.incbin "graphics/en/menu/bracket.4bpp"

	.align 2
	.global gEnMenuObjPal
gEnMenuObjPal:
	.incbin "graphics/en/menu/menu_obj.gbapal"

	.align 2
	.global gEnPlateFont
gEnPlateFont:
	.incbin "graphics/en/menu/plate_font.bin"

	.align 2
	.global gEnPlateFontAdv
gEnPlateFontAdv:
	.incbin "graphics/en/menu/plate_font_adv.bin"

	.align 2
	.global gEnPlateFontOff
gEnPlateFontOff:
	.incbin "graphics/en/menu/plate_font_off.bin"
