@ generated by tools/en/port_new_sounds.py
	.include "asm/macros.inc"
	.section en_data, "a"

	.align 2
gEnSongSE04F_voice:
	voice_directsound 60, 0, gEnSongSE04F_sample, 255, 0, 255, 0

gEnSongSE04F_track:
	.byte 0xBC, 0x00, 0xBB, 0x3C, 0xBD, 0x00, 0xBE, 70, 0xBF, 0x40
	.byte 0xFF, 0x3C, 0x7F, 0xB0, 0xB1

	.align 2
	.global gEnSongSE04F
gEnSongSE04F:
	.byte 1, 0, 127, 128
	.word gEnSongSE04F_voice
	.word gEnSongSE04F_track

	.align 2
gEnSongSE04F_sample:
	.incbin "sound/direct_sound_samples/en_se04f.bin"

	.align 2
gEnSongSE050_voice:
	voice_directsound 60, 0, gEnSongSE050_sample, 255, 0, 255, 0

gEnSongSE050_track:
	.byte 0xBC, 0x00, 0xBB, 0x3C, 0xBD, 0x00, 0xBE, 78, 0xBF, 0x40
	.byte 0xFF, 0x3C, 0x7F, 0xB0, 0xB1

	.align 2
	.global gEnSongSE050
gEnSongSE050:
	.byte 1, 0, 127, 128
	.word gEnSongSE050_voice
	.word gEnSongSE050_track

	.align 2
gEnSongSE050_sample:
	.incbin "sound/direct_sound_samples/en_se050.bin"
