@ generated by tools/en/port_sfx.py: the DS sound effects
	.include "asm/macros.inc"
	.section en_data, "a"

@ song 55: DS SE0B5, volume 109
	.align 2
gEnSfx055_voices:
	voice_directsound_no_resample 60, 0, gEnSfxSample_26418822b1, 255, 0, 255, 19
gEnSfx055_track0:
	.byte 0xBC, 0x00, 0xBB, 0x78, 0xBE, 0x6D, 0xBF, 0x40, 0xBD, 0x00, 0xCF, 0x3C, 0x7F, 0xB0, 0xB0, 0xB0, 0xB0, 0xCE, 0x3C, 0xB1
	.align 2
	.global gEnSfx055
gEnSfx055:
	.byte 1, 0, 80, 0x80
	.word gEnSfx055_voices
	.word gEnSfx055_track0

@ song 56: DS SE0B3, volume 109
	.align 2
gEnSfx056_voices:
	voice_directsound_no_resample 60, 0, gEnSfxSample_358915c200, 255, 0, 255, 19
gEnSfx056_track0:
	.byte 0xBC, 0x00, 0xBB, 0x78, 0xBE, 0x6D, 0xBF, 0x40, 0xBD, 0x00, 0xCF, 0x3C, 0x7F, 0xB0, 0xB0, 0xB0, 0xB0, 0xCE, 0x3C, 0xB1
	.align 2
	.global gEnSfx056
gEnSfx056:
	.byte 1, 0, 80, 0x80
	.word gEnSfx056_voices
	.word gEnSfx056_track0

@ song 57: DS SE0B2, volume 110
	.align 2
gEnSfx057_voices:
	voice_directsound_no_resample 60, 0, gEnSfxSample_b654276cbe, 255, 0, 255, 19
gEnSfx057_track0:
	.byte 0xBC, 0x00, 0xBB, 0x78, 0xBE, 0x6E, 0xBF, 0x40, 0xBD, 0x00, 0xCF, 0x3C, 0x7F, 0xB0, 0xB0, 0xB0, 0xB0, 0xCE, 0x3C, 0xB1
	.align 2
	.global gEnSfx057
gEnSfx057:
	.byte 1, 0, 80, 0x80
	.word gEnSfx057_voices
	.word gEnSfx057_track0

@ song 65: DS SE0B4, volume 110
	.align 2
gEnSfx065_voices:
	voice_directsound_no_resample 60, 0, gEnSfxSample_17f78c21ac, 255, 0, 255, 19
gEnSfx065_track0:
	.byte 0xBC, 0x00, 0xBB, 0x78, 0xBE, 0x6E, 0xBF, 0x40, 0xBD, 0x00, 0xCF, 0x3C, 0x7F, 0xB0, 0xB0, 0xB0, 0xB0, 0xCE, 0x3C, 0xB1
	.align 2
	.global gEnSfx065
gEnSfx065:
	.byte 1, 0, 127, 0x80
	.word gEnSfx065_voices
	.word gEnSfx065_track0

@ song 71: DS SE0B1, volume 94
	.align 2
gEnSfx071_voices:
	voice_directsound_no_resample 60, 0, gEnSfxSample_fe9776731c, 255, 0, 255, 19
gEnSfx071_track0:
	.byte 0xBC, 0x00, 0xBB, 0x78, 0xBE, 0x5E, 0xBF, 0x40, 0xBD, 0x00, 0xCF, 0x3C, 0x7F, 0xB0, 0xB0, 0xB0, 0xB0, 0xCE, 0x3C, 0xB1
	.align 2
	.global gEnSfx071
gEnSfx071:
	.byte 1, 0, 127, 0x80
	.word gEnSfx071_voices
	.word gEnSfx071_track0

@ song 81: DS SE0B0, volume 109
	.align 2
gEnSfx081_voices:
	voice_directsound_no_resample 60, 0, gEnSfxSample_7d5ad12369, 255, 0, 255, 19
gEnSfx081_track0:
	.byte 0xBC, 0x00, 0xBB, 0x78, 0xBE, 0x6D, 0xBF, 0x40, 0xBD, 0x00, 0xCF, 0x3C, 0x7F, 0xB0, 0xB0, 0xB0, 0xB0, 0xCE, 0x3C, 0xB1
	.align 2
	.global gEnSfx081
gEnSfx081:
	.byte 1, 0, 127, 0x80
	.word gEnSfx081_voices
	.word gEnSfx081_track0

@ song 111: DS SE04F, volume 76
	.align 2
gEnSfx111_voices:
	voice_directsound_no_resample 60, 0, gEnSfxSample_63004dde45, 255, 0, 255, 19
gEnSfx111_track0:
	.byte 0xBC, 0x00, 0xBB, 0x78, 0xBE, 0x4C, 0xBF, 0x40, 0xBD, 0x00, 0xFE, 0x3C, 0x7F, 0xAF, 0xB1
	.align 2
	.global gEnSfx111
gEnSfx111:
	.byte 1, 0, 127, 0x80
	.word gEnSfx111_voices
	.word gEnSfx111_track0

@ song 112: DS SE050, volume 85
	.align 2
gEnSfx112_voices:
	voice_directsound_no_resample 60, 0, gEnSfxSample_138b992ee7, 255, 0, 255, 19
gEnSfx112_track0:
	.byte 0xBC, 0x00, 0xBB, 0x78, 0xBE, 0x55, 0xBF, 0x40, 0xBD, 0x00, 0xFE, 0x3C, 0x7F, 0xAF, 0xB1
	.align 2
	.global gEnSfx112
gEnSfx112:
	.byte 1, 0, 127, 0x80
	.word gEnSfx112_voices
	.word gEnSfx112_track0

	.align 2
gEnSfxSample_138b992ee7:
	.incbin "sound/direct_sound_samples/en_sfx/138b992ee7.bin"
	.align 2
gEnSfxSample_17f78c21ac:
	.incbin "sound/direct_sound_samples/en_sfx/17f78c21ac.bin"
	.align 2
gEnSfxSample_26418822b1:
	.incbin "sound/direct_sound_samples/en_sfx/26418822b1.bin"
	.align 2
gEnSfxSample_358915c200:
	.incbin "sound/direct_sound_samples/en_sfx/358915c200.bin"
	.align 2
gEnSfxSample_63004dde45:
	.incbin "sound/direct_sound_samples/en_sfx/63004dde45.bin"
	.align 2
gEnSfxSample_7d5ad12369:
	.incbin "sound/direct_sound_samples/en_sfx/7d5ad12369.bin"
	.align 2
gEnSfxSample_b654276cbe:
	.incbin "sound/direct_sound_samples/en_sfx/b654276cbe.bin"
	.align 2
gEnSfxSample_fe9776731c:
	.incbin "sound/direct_sound_samples/en_sfx/fe9776731c.bin"
