// generated by tools/en/port_gs3_court.py: the courtroom pans of
// Gyakuten Saiban 3 (camera position on each of the 16 frames of each pan,
// in pixels along the picture: defense bench 0, witness stand 520,
// prosecution bench 1040)
#define EN_PAN_FRAME_SIZE 0x9800
#define EN_PAN_SWAP_FRAME 9
static const s16 sEnPanCamera[3][16] = {
    {0, 8, 16, 24, 40, 64, 96, 144, 200, 264, 336, 416, 504, 512, 520, 520},
    {1040, 1024, 1008, 992, 936, 840, 744, 640, 536, 432, 328, 224, 128, 32, 16, 0},
    {1040, 1032, 1024, 1016, 1000, 976, 944, 896, 840, 776, 704, 624, 536, 528, 520, 520},
};
static const s16 sEnPanView[3][2] = {
    {0, 520}, // defense_bench -> witness_stand
    {1040, 0}, // prosecution_bench -> defense_bench
    {1040, 520}, // prosecution_bench -> witness_stand
};
