// generated by tools/en/make_effects.py
#ifndef GUARD_EN_EFFECTS_H
#define GUARD_EN_EFFECTS_H

extern u8 gEnBannerGfx[];
extern u8 gEnBannerSeq_testimony[];
extern u8 gEnBannerSeq_cross[];
extern u8 gEnBannerSeq_testimony_left[];
extern u8 gEnBannerSeq_testimony_right[];
extern u8 gEnBannerSeq_cross_left[];
extern u8 gEnBannerSeq_cross_right[];
extern u8 gEnBubbleGfx_objection[];
extern u8 gEnBubbleSeq_objection[];
#define EN_BUBBLE_SPRITES_OBJECTION 27
extern u8 gEnBubbleGfx_holdit[];
extern u8 gEnBubbleSeq_holdit[];
#define EN_BUBBLE_SPRITES_HOLDIT 13
extern u8 gEnBubbleGfx_takethat[];
extern u8 gEnBubbleSeq_takethat[];
#define EN_BUBBLE_SPRITES_TAKETHAT 21

extern const u8 gEnVerdictLetterTiles[];
extern const u16 gEnVerdictPalGuilty[];
extern const u16 gEnVerdictPalNotGuilty[];

// one sprite per letter; vram is an offset into OBJ_VRAM0, (x, y) the
// top-left of the double-size affine box, delay in frames
struct VerdictLetter { u16 vram; u16 src; u16 size; u8 tall; u8 delay; s16 x; s16 y; };
#ifdef EN_VERDICT_TABLES
static const struct VerdictLetter gVerdictLettersGuilty[] = {
    { 0x5000, 0x1000, 0x800, 0, 10,    3,   -7 },
    { 0x4C00, 0x1800, 0x400, 1, 20,   66,   -7 },
    { 0x4800, 0x1C00, 0x400, 1, 30,   87,   -7 },
    { 0x4400, 0x2000, 0x400, 1, 40,  103,   -7 },
    { 0x4000, 0x2400, 0x400, 1, 50,  120,   -7 },
    { 0x3C00, 0x2800, 0x400, 1, 60,  146,   -7 },
};
static const struct VerdictLetter gVerdictLettersNotGuilty[] = {
    { 0x5000, 0x0000, 0x800, 0,  0,  -41,   -7 },
    { 0x4C00, 0x0800, 0x400, 1,  0,   20,   -7 },
    { 0x4800, 0x0C00, 0x400, 1,  0,   42,   -7 },
    { 0x4000, 0x1000, 0x800, 0, 60,   45,   -7 },
    { 0x3C00, 0x1800, 0x400, 1, 60,  108,   -7 },
    { 0x3800, 0x1C00, 0x400, 1, 60,  129,   -7 },
    { 0x3400, 0x2000, 0x400, 1, 60,  146,   -7 },
    { 0x3000, 0x2400, 0x400, 1, 60,  163,   -7 },
    { 0x2C00, 0x2800, 0x400, 1, 60,  188,   -7 },
};
#endif

#endif
