// generated by tools/en/make_menus.py
#ifndef GUARD_EN_MENU_GFX_H
#define GUARD_EN_MENU_GFX_H

extern const u8 gEnMenuBgTiles[];
extern const u16 gEnMenuBgPal[];
extern const u16 gEnMenuMapSave[];
extern const u16 gEnMenuMapLoad[];
extern const u16 gEnMenuMapClear[];
extern const u8 gEnMenuButtonsShort[];
extern const u8 gEnMenuButtonsLong[];
extern const u8 gEnMenuBracket[];
extern const u16 gEnMenuObjPal[];
extern const u8 gEnPlateFont[];
extern const u8 gEnPlateFontAdv[];
extern const u8 gEnPlateFontOff[];

#define EN_MENU_BG_TILE_BASE 128
#define EN_MENU_BG_TILE_COUNT 205
#define EN_MENU_BG_PAL 3
#define EN_MENU_STRIPE_TILE 129
#define EN_MENU_SHORT_BUTTON_BYTES 1536
#define EN_MENU_LONG_BUTTON_BYTES 3072
#define EN_PLATE_FONT_CODES 272
#define EN_PLATE_FONT_ROWS 14

#endif // GUARD_EN_MENU_GFX_H
